[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  base = "Noteflix/"

[[redirects]]
from = "/*"
to = "/index.php"
status = 200
