# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - noteflix

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_024cf3f810504077aede3e7e9074c2c5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0c1b3747838e441ea0ef121a5d6011fa }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_024cf3f810504077aede3e7e9074c2c5 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'noteflix'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7abd200be1ba49509fedca1b25ba6c36 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_024cf3f810504077aede3e7e9074c2c5 }}/appsvc/staticsite:${{ github.sha }}'